### PR TITLE
platform and port specific files into seperate directories

### PR DESCRIPTION
**Pull request by nanosonde**
This pull request puts platform and port specific files into seperate directories as suggested here:
https://github.com/thelsing/knx/issues/6

It is basically the structure that btstack uses.
Arduino is just another platform next to the linux platform.
Maybe one should also add a similar Makefile like [this](https://github.com/bluekitchen/btstack/blob/master/port/arduino/Makefile) one which adds a convient way to generate the knx arduino library.

knxPython (from my point of view) is just another port of the knx stack.

Visualstudio files have also been moved and the paths were updated.

### CODE REVIEW

**Comment by nanosonde** [comment]
Looking through the esp_platform.* and samd_platform.* files I realized that it does not make sense to put them into additional directories as they all use stuff from the arduino framework.

Another port and platform I am currently looking at is ESP32 (without Wifi, only BLE) with ESP-IDF and RTOS.

**Comment by nanosonde** [comment]
Are you going to consider this PR?
Otherwise, I will stop working on it.

**Comment by thelsing** [comment]
I have not testet it yet. If my usual workflow still works I'll merge this. The repository can't be used as a arduino lib directly after this, right?

**Comment by nanosonde** [comment]
That's correct. It won't work as arduino lib anymore directly.
Therefore I have provided in the port/arduino folder. Just run it in the folder and it creates a ZIP file which contains all arduino source files in a single directory.

My suggestion would be to setup Travis-CI for this repository and whenever you create a tagged release then CI runs this make file and uploads the ZIP file to the Github release page.

**Pull request closed without merging**
