### PR TITLE
opt-out global KNX, ability to DIY construct knx object, minor cleanups

### PR DESCRIPTION
**Pull request by defl**
Refactored the knx_facade a bit to make the auto-building of the global knx object and the buttonUp() ISR function opt-in. Also added the ability to quite easily attach another serial (in this case tested with Serial2 of an ESP32).

(Didn't test with opt-in building yet, assumed comments would follow so won't spend time there yet.)

### CODE REVIEW

**Comment by thelsing** [comment]
Can you please fix the build checks? Also the default knx instance should be enabled as a default to avoid breaking things for people.

**Comment by defl** [comment]
Fixed tests for platformio locally, will take a look at the failing other ones later.

**Comment by defl** [comment]
All passes now. In the end there is one breaking change for in case where they in Linux have made their own button handler and are calling the now private _toogleProgMode (note the typo in the name which was in the code already). That has been replaced by need to call toggleProgMode(); (b7c67f0)

**Comment by thelsing** [comment]
Merged, thanks.

**Pull request merged**
