### PR TITLE
solves #178 bugfix when sending frames > 63 byte, missing masking of …

### PR DESCRIPTION
**Pull request by SirSydom**
…upper bits after sending a U_DataOffset

### CODE REVIEW

**Review by mptei — CHANGES_REQUESTED** [review]
Why the modulo operation?
Using a simple "& 0x3f" is sufficient here, or?

This change works only up to 127 bytes.  U_L_DATA_END_REQ needs that mask to.

**Comment by SirSydom** [comment]
> Why the modulo operation?
> Using a simple "& 0x3f" is sufficient here, or?

sufficient yes. I doubt it will make any difference in opcode, since compiler optimize such stuff anyway.
But in my view is much more readable.

the function starts with
`uint8_t idx = _TxByteCnt / 64;`
could also be written as `uint8_t idx = _TxByteCnt >> 5;`
but isn't, because it is not very readable.

here _TxByteCnt is split and the lower part is used - _TxByteCnt % 64 gets the upper part.
For me that is absolutely logical.


> U_L_DATA_END_REQ needs that mask to.
you're right. missed that one.

**Comment by mptei** [comment]
> But in my view is much more readable.

This is just the problem. Here we are in bit banging world. Masking via & is easy to understand. Replacing this by % is possible in this specific case, but generally not.

You pointed exactly at the other place what I would change, Shifting bits is easy to understand when a shift operator is used. Expressing this by a division simply hides what's going on here.

We want to shift bits around, mask them and combine them. We don't want to solve mathematical problems.

**Comment by SirSydom** [comment]
>We want to shift bits around, mask them and combine them. We don't want to solve mathematical problems.

bitbanging IS a way of solving mathemtical problems in a very hardware-dependent manner.
using higher level operations is a more abstract approach.

I oriented myself on the used division and I generally use division and modulo for splitting numbers up into smaller numbers with different place values.

But in the end I don't really care how it is solved.
If you make a PR changing the solution to one using pure bit operations I'm really fine.
@thelsing Thomas should decide what fits into his stack.

**Comment by thelsing** [comment]
```
$ cat test_mod.c test_and.c
#include <stdio.h>
int main (int argc, char *argv[])
{
printf("%d d\n", argc %64);
return 0;
}
#include <stdio.h>
int main (int argc, char *argv[])
{
printf("%d d\n", argc & 0x3f);
return 0;
}
$ gcc -O2 -s test_and.c
$ gcc -O2 -s test_mod.c
$ diff -u test_and.c test_mod.c
--- test_and.c  2022-02-23 20:29:07.829008200 +0100
+++ test_mod.c  2022-02-23 20:26:44.699008200 +0100
@@ -1,6 +1,6 @@
 #include <stdio.h>
 int main (int argc, char *argv[])
 {
-printf("%d d\n", argc & 0x3f);
+printf("%d d\n", argc %64);
 return 0;
 }
$ diff -u test_and.s test_mod.s
--- test_and.s  2022-02-23 20:26:16.859008200 +0100
+++ test_mod.s  2022-02-23 20:26:48.939008200 +0100
@@ -10,12 +10,16 @@
 main:
 .LFB11:
        .cfi_startproc
-       movl    %edi, %esi
+       movl    %edi, %eax
        subq    $8, %rsp
        .cfi_def_cfa_offset 16
+       sarl    $31, %eax
+       shrl    $26, %eax
+       leal    (%rdi,%rax), %esi
        leaq    .LC0(%rip), %rdi
-       xorl    %eax, %eax
        andl    $63, %esi
+       subl    %eax, %esi
+       xorl    %eax, %eax
        call    printf@PLT
        xorl    %eax, %eax
        addq    $8, %rsp
```
I also like & and << better in such case. The example also shows thats it's faster. It would be nice if you could replace the /  64 with a shift.

**Comment by thelsing** [comment]
Merged. Thanks.

**Pull request merged**
