### PR TITLE
Improve property description handling

### PR DESCRIPTION
**Pull request by nanosonde**
Hi!
Please consider merging this pull request.

### CODE REVIEW

**Comment by nanosonde** [comment]
Hi!
With these fixes and additions it works with ETS5 and Net'n'Node.
Please see the inline comments from the last commit to understand the fixes.

**Comment by nanosonde** [comment]
I hope everything is alright now. Please check again.

**Comment by thelsing** [comment]
Everything is fine now. Thanks. Which tool did you use for finding the unnecessary spaces?

**Comment by nanosonde** [comment]
I have used NotePad++ to make the changes.
Edit->Blank Operations->Trim trailing spaces

**Pull request merged**
